services:
  blog:
    image: dockerhub.aganitha.ai:4443/blog_hk/blog-astro:latest
    container_name: blog-astro
    ports:
      - "8080:80"
    restart: unless-stopped

    labels:
      - user=harleen
      - description="Astro blog"
      - security=none